### ISSUE TITLE
Map not rendering (ReferenceError: Can't find variable: loadMapLibrary)

### ISSUE THREAD

**Issue by alvarolozano** [dlemmermann/GMapsFX#192]
A long time ago I started my project with this library, yesterday it was working, but today it doesn't render the map, I tried to import the demos, but same result. If I enable debug (with the GoogleMapView constructor), it thows a JavaScript exception: **ReferenceError: Can't find variable: loadMapLibrary**

**Comment by HarmHoog** [comment]
You can add merge request #191 to the library, that should fix the problem.

**Comment by dlemmermann** [comment]
PR #191 was merged.
